import type { Scheme } from "./types"

export const SCHEMES: Scheme[] = [
  // Education (3)
  {
    id: "edu-1",
    name: "National Scholarship Portal (NSP)",
    domain: "Education",
    description: "Central scholarship scheme for students from economically weaker sections pursuing higher education. Provides financial support for tuition fees, living expenses, and academic materials.",
    minAge: 16,
    maxAge: 35,
    incomeLimit: 250000,
    occupationRequired: ["Student"],
    genderRequired: null,
    benefits: "Up to Rs 50,000 per year for tuition and living expenses. Priority admission in government institutions.",
    risks: "Must maintain minimum 60% attendance. Scholarship revoked if academic performance drops below threshold.",
    requiredDocuments: ["Aadhaar Card", "Income Certificate", "Mark Sheets", "Bank Account Details", "Caste Certificate (if applicable)"],
    estimatedFinancialImpact: 50000,
    officialPortalUrl: "https://scholarships.gov.in/",
  },
  {
    id: "edu-2",
    name: "Skill India Training Program",
    domain: "Education",
    description: "Free vocational training in high-demand sectors like IT, healthcare, and manufacturing. Includes certification recognized by industry partners.",
    minAge: 18,
    maxAge: 45,
    incomeLimit: 300000,
    occupationRequired: ["Unemployed", "Student", "Farmer"],
    genderRequired: null,
    benefits: "Free 3-6 month training with industry certification. Monthly stipend of Rs 5,000 during training period. Job placement assistance.",
    risks: "Limited seats per batch. Training centers may not be available in all regions.",
    requiredDocuments: ["Aadhaar Card", "Education Certificates", "Bank Account Details"],
    estimatedFinancialImpact: 30000,
    officialPortalUrl: "https://www.skillindia.gov.in/",
  },
  {
    id: "edu-3",
    name: "Digital Literacy Mission",
    domain: "Education",
    description: "Program to impart digital literacy to rural households, covering basic computer operations, internet usage, and digital payments.",
    minAge: 14,
    maxAge: 60,
    incomeLimit: 200000,
    occupationRequired: ["Student", "Farmer", "Unemployed", "Self-employed"],
    genderRequired: null,
    benefits: "Free 20-hour digital literacy course. Free tablet or laptop for top performers. Digital payment training.",
    risks: "Course available only at designated training centers. Internet connectivity issues in rural areas.",
    requiredDocuments: ["Aadhaar Card", "Address Proof", "Age Proof"],
    estimatedFinancialImpact: 15000,
    officialPortalUrl: "https://www.digitalindia.gov.in/",
  },

  // Agriculture (3)
  {
    id: "agri-1",
    name: "PM-KISAN Samman Nidhi",
    domain: "Agriculture",
    description: "Direct income support of Rs 6,000 per year to small and marginal farmer families, paid in three equal installments directly to bank accounts.",
    minAge: 18,
    maxAge: 80,
    incomeLimit: 500000,
    occupationRequired: ["Farmer"],
    genderRequired: null,
    benefits: "Rs 6,000 annual direct benefit transfer. No collateral required. Automatic enrollment for crop insurance.",
    risks: "Land ownership disputes may delay processing. Installment delays possible during verification.",
    requiredDocuments: ["Aadhaar Card", "Land Ownership Records", "Bank Account Details", "State Farmer ID"],
    estimatedFinancialImpact: 6000,
    officialPortalUrl: "https://pmkisan.gov.in/",
  },
  {
    id: "agri-2",
    name: "Kisan Credit Card (KCC)",
    domain: "Agriculture",
    description: "Provides affordable short-term credit to farmers for cultivation, post-harvest expenses, and allied agricultural activities at subsidized interest rates.",
    minAge: 18,
    maxAge: 70,
    incomeLimit: 800000,
    occupationRequired: ["Farmer", "Self-employed"],
    genderRequired: null,
    benefits: "Credit up to Rs 3 lakhs at 4% interest. Crop insurance coverage included. Flexible repayment schedule.",
    risks: "Overdue payments attract penalty interest. Credit limit based on land holding size.",
    requiredDocuments: ["Aadhaar Card", "Land Records", "Bank Account", "Passport Size Photo", "Identity Proof"],
    estimatedFinancialImpact: 300000,
    officialPortalUrl: "https://www.kisancreditcard.com/",
  },
  {
    id: "agri-3",
    name: "Soil Health Card Scheme",
    domain: "Agriculture",
    description: "Provides soil testing and health cards to farmers with crop-wise fertilizer recommendations to improve productivity and reduce input costs.",
    minAge: 18,
    maxAge: 80,
    incomeLimit: 1000000,
    occupationRequired: ["Farmer"],
    genderRequired: null,
    benefits: "Free soil testing every 2 years. Customized fertilizer recommendations. Up to 20% reduction in input costs.",
    risks: "Testing labs may have backlogs. Recommendations require adoption of new practices.",
    requiredDocuments: ["Aadhaar Card", "Land Records", "Farmer Registration"],
    estimatedFinancialImpact: 10000,
    officialPortalUrl: "https://soilhealth.dac.gov.in/",
  },

  // Health (3)
  {
    id: "health-1",
    name: "Ayushman Bharat (PM-JAY)",
    domain: "Health",
    description: "Flagship health insurance scheme providing Rs 5 lakh per family per year for secondary and tertiary hospitalization. Covers pre and post-hospitalization expenses.",
    minAge: 0,
    maxAge: 100,
    incomeLimit: 300000,
    occupationRequired: ["Student", "Farmer", "Salaried", "Self-employed", "Government", "Unemployed", "Housewife", "Homemaker", "Retired", "Daily wage worker"],
    genderRequired: null,
    benefits: "Rs 5 lakh health coverage per family per year. Cashless treatment at empaneled hospitals. Covers 1,500+ procedures.",
    risks: "Not all hospitals are empaneled. Pre-existing conditions have waiting period. Claim process may take time.",
    requiredDocuments: ["Aadhaar Card", "Ration Card", "Income Certificate", "Family Details"],
    estimatedFinancialImpact: 500000,
    officialPortalUrl: "https://pmjay.gov.in/",
  },
  {
    id: "health-2",
    name: "Janani Suraksha Yojana",
    domain: "Health",
    description: "Cash incentive scheme for pregnant women to encourage institutional delivery, reduce maternal and neonatal mortality, especially in rural areas.",
    minAge: 18,
    maxAge: 45,
    incomeLimit: 250000,
    occupationRequired: ["Student", "Farmer", "Salaried", "Self-employed", "Unemployed", "Housewife", "Homemaker"],
    genderRequired: "Female",
    benefits: "Rs 1,400 cash benefit for rural deliveries, Rs 1,000 for urban. Free antenatal check-ups. Free transport to hospital.",
    risks: "Applicable only for first two live births. Must deliver at government or accredited hospital.",
    requiredDocuments: ["Aadhaar Card", "BPL Card", "MCH Card", "Bank Account Details"],
    estimatedFinancialImpact: 1400,
    officialPortalUrl: "https://nhm.gov.in/",
  },
  {
    id: "health-3",
    name: "National Health Mission (NHM) Outreach",
    domain: "Health",
    description: "Mobile health units providing primary healthcare services in underserved rural and tribal areas, including diagnostics, medicine distribution, and referral services.",
    minAge: 0,
    maxAge: 100,
    incomeLimit: 400000,
    occupationRequired: ["Student", "Farmer", "Salaried", "Self-employed", "Government", "Unemployed", "Housewife", "Homemaker", "Retired", "Daily wage worker"],
    genderRequired: null,
    benefits: "Free primary healthcare services. Free essential medicines. Doorstep diagnostic services in remote areas.",
    risks: "Service availability depends on mobile unit schedule. Limited to primary care only.",
    requiredDocuments: ["Aadhaar Card", "Address Proof"],
    estimatedFinancialImpact: 5000,
    officialPortalUrl: "https://nhm.gov.in/",
  },

  // Women (2)
  {
    id: "women-1",
    name: "Beti Bachao Beti Padhao",
    domain: "Women",
    description: "Comprehensive program addressing declining child sex ratio and promoting education of girl children through awareness campaigns and direct support.",
    minAge: 0,
    maxAge: 25,
    incomeLimit: 400000,
    occupationRequired: ["Student", "Unemployed", "Housewife", "Homemaker"],
    genderRequired: "Female",
    benefits: "Sukanya Samriddhi Account with tax benefits. Scholarship for higher education. Skill training workshops.",
    risks: "Some benefits available only through Sukanya Samriddhi Account. Long-term commitment required.",
    requiredDocuments: ["Birth Certificate", "Aadhaar Card", "Parent Aadhaar", "Bank Account Details"],
    estimatedFinancialImpact: 25000,
    officialPortalUrl: "https://wcd.nic.in/bbbp-scheme",
  },
  {
    id: "women-2",
    name: "Mahila Shakti Kendra",
    domain: "Women",
    description: "Empowerment program providing skill development, employment opportunities, digital literacy, and healthcare awareness specifically for rural women.",
    minAge: 18,
    maxAge: 55,
    incomeLimit: 300000,
    occupationRequired: ["Farmer", "Self-employed", "Unemployed", "Housewife", "Homemaker"],
    genderRequired: "Female",
    benefits: "Free skill development training. Micro-loan facility up to Rs 1 lakh. Self-help group formation support.",
    risks: "Limited to block-level implementation. Micro-loan requires group guarantee.",
    requiredDocuments: ["Aadhaar Card", "Address Proof", "Income Certificate", "Bank Account"],
    estimatedFinancialImpact: 100000,
    officialPortalUrl: "https://wcd.nic.in/",
  },

  // Senior (2)
  {
    id: "senior-1",
    name: "Indira Gandhi National Old Age Pension",
    domain: "Senior",
    description: "Monthly pension for senior citizens from BPL families. Provides financial security for elderly individuals without other sources of income or family support.",
    minAge: 60,
    maxAge: 100,
    incomeLimit: 200000,
    occupationRequired: ["Unemployed", "Farmer", "Self-employed", "Retired", "Housewife", "Homemaker"],
    genderRequired: null,
    benefits: "Rs 500/month pension (60-79 years). Rs 800/month pension (80+ years). Direct transfer to bank account.",
    risks: "Pension amount may not cover all living expenses. Annual verification required.",
    requiredDocuments: ["Aadhaar Card", "Age Proof", "BPL Card", "Bank Account Details"],
    estimatedFinancialImpact: 6000,
    officialPortalUrl: "https://nsap.nic.in/",
  },
  {
    id: "senior-2",
    name: "Rashtriya Vayoshri Yojana",
    domain: "Senior",
    description: "Provides free physical aids and assisted-living devices to senior citizens belonging to BPL category who suffer from age-related disabilities.",
    minAge: 60,
    maxAge: 100,
    incomeLimit: 200000,
    occupationRequired: ["Unemployed", "Farmer", "Self-employed", "Salaried", "Retired"],
    genderRequired: null,
    benefits: "Free walking sticks, hearing aids, wheelchairs, spectacles. Free fitting and maintenance for one year.",
    risks: "Limited to specific disability categories. Distribution camps held periodically, not on-demand.",
    requiredDocuments: ["Aadhaar Card", "BPL Certificate", "Disability Certificate", "Age Proof"],
    estimatedFinancialImpact: 10000,
    officialPortalUrl: "https://www.socialjustice.nic.in/",
  },

  // MSME (1)
  {
    id: "msme-1",
    name: "MUDRA Loan Scheme",
    domain: "MSME",
    description: "Collateral-free loans for micro and small enterprises under three categories: Shishu (up to 50K), Kishore (50K-5L), and Tarun (5L-10L).",
    minAge: 18,
    maxAge: 65,
    incomeLimit: 600000,
    occupationRequired: ["Self-employed", "Farmer", "Daily wage worker"],
    genderRequired: null,
    benefits: "Collateral-free loans up to Rs 10 lakhs. Subsidized interest rates. Quick processing within 7-10 days.",
    risks: "Higher interest for Tarun category. Business plan evaluation required. Repayment default affects credit score.",
    requiredDocuments: ["Aadhaar Card", "Business Plan", "Address Proof", "Bank Statements", "Business Registration (if any)"],
    estimatedFinancialImpact: 1000000,
    officialPortalUrl: "https://www.mudra.org.in/",
  },

  // Financial Inclusion (1)
  {
    id: "fin-1",
    name: "Pradhan Mantri Jan Dhan Yojana",
    domain: "Financial",
    description: "Universal financial inclusion program providing zero-balance bank accounts with RuPay debit card, accident insurance, and overdraft facility.",
    minAge: 10,
    maxAge: 100,
    incomeLimit: 1000000,
    occupationRequired: ["Student", "Farmer", "Salaried", "Self-employed", "Government", "Unemployed", "Housewife", "Homemaker", "Retired", "Daily wage worker"],
    genderRequired: null,
    benefits: "Zero-balance savings account. Free RuPay debit card. Rs 2 lakh accident insurance. Rs 10,000 overdraft facility.",
    risks: "Overdraft requires active account usage. Insurance claim requires documentation.",
    requiredDocuments: ["Aadhaar Card", "Address Proof", "Passport Size Photo"],
    estimatedFinancialImpact: 200000,
    officialPortalUrl: "https://pmjdy.gov.in/",
  },
]
